// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.13.0
// source: users/user_input.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	generic "skeleton/pb/generic"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserListInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids        []string            `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Emails     []string            `protobuf:"bytes,2,rep,name=emails,proto3" json:"emails,omitempty"`
	Pagination *generic.Pagination `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *UserListInput) Reset() {
	*x = UserListInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_user_input_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListInput) ProtoMessage() {}

func (x *UserListInput) ProtoReflect() protoreflect.Message {
	mi := &file_users_user_input_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListInput.ProtoReflect.Descriptor instead.
func (*UserListInput) Descriptor() ([]byte, []int) {
	return file_users_user_input_proto_rawDescGZIP(), []int{0}
}

func (x *UserListInput) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UserListInput) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *UserListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UserCreateInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username   string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email      string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	RePassword string `protobuf:"bytes,4,opt,name=re_password,json=rePassword,proto3" json:"re_password,omitempty"`
}

func (x *UserCreateInput) Reset() {
	*x = UserCreateInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_user_input_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCreateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateInput) ProtoMessage() {}

func (x *UserCreateInput) ProtoReflect() protoreflect.Message {
	mi := &file_users_user_input_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateInput.ProtoReflect.Descriptor instead.
func (*UserCreateInput) Descriptor() ([]byte, []int) {
	return file_users_user_input_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreateInput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreateInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreateInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreateInput) GetRePassword() string {
	if x != nil {
		return x.RePassword
	}
	return ""
}

var File_users_user_input_proto protoreflect.FileDescriptor

var file_users_user_input_proto_rawDesc = []byte{
	0x0a, 0x16, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74,
	0x6f, 0x6e, 0x1a, 0x1d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2f, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6f, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x03, 0x69, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x34, 0x0a, 0x0a,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x80, 0x01, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x19, 0x5a, 0x17, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f,
	0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_users_user_input_proto_rawDescOnce sync.Once
	file_users_user_input_proto_rawDescData = file_users_user_input_proto_rawDesc
)

func file_users_user_input_proto_rawDescGZIP() []byte {
	file_users_user_input_proto_rawDescOnce.Do(func() {
		file_users_user_input_proto_rawDescData = protoimpl.X.CompressGZIP(file_users_user_input_proto_rawDescData)
	})
	return file_users_user_input_proto_rawDescData
}

var file_users_user_input_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_users_user_input_proto_goTypes = []interface{}{
	(*UserListInput)(nil),      // 0: skeleton.UserListInput
	(*UserCreateInput)(nil),    // 1: skeleton.UserCreateInput
	(*generic.Pagination)(nil), // 2: skeleton.Pagination
}
var file_users_user_input_proto_depIdxs = []int32{
	2, // 0: skeleton.UserListInput.pagination:type_name -> skeleton.Pagination
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_users_user_input_proto_init() }
func file_users_user_input_proto_init() {
	if File_users_user_input_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_users_user_input_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserListInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_user_input_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCreateInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_users_user_input_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_user_input_proto_goTypes,
		DependencyIndexes: file_users_user_input_proto_depIdxs,
		MessageInfos:      file_users_user_input_proto_msgTypes,
	}.Build()
	File_users_user_input_proto = out.File
	file_users_user_input_proto_rawDesc = nil
	file_users_user_input_proto_goTypes = nil
	file_users_user_input_proto_depIdxs = nil
}
